# Generated by Django 3.0.7 on 2020-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hospital',
            field=models.ManyToManyField(to='hospitals.Hospital'),
        ),
    ]
