# Generated by Django 3.0.7 on 2020-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('accounts', '0002_account_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hospital',
            field=models.ManyToManyField(blank=True, to='hospitals.Hospital'),
        ),
    ]
