# Generated by Django 3.0.7 on 2020-08-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200726_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_users', to='accounts.HospitalStaff'),
        ),
    ]
