# Generated by Django 3.0.7 on 2020-07-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='PPE_kits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='PPE_kits_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bleaching_powder',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='chemical_gloves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='handwash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ice_gel_pack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='infrared_thermometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='n95_masks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='rubbing_alcohol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sanitizer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sodium_hypochlorite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='swap_sticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='three_layer_masks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='three_layer_packing_mask',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='viral_transport_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='hospitals.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(blank='', choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50),
        ),
    ]
